### ISSUE TITLE
mapファイルの置き場所

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT-Unit03/cirkit_unit03_navigation#2]
とりあえず move_base pkg配下に入れてあります．

どこか適切な場所に移すべき，という議論があったと思います．

**Comment by AriYu** [comment]
https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/20#issuecomment-262902799

**Comment by MoriKen254** [comment]
解決しましたので，閉じます．

https://github.com/CIR-KIT-Unit03/cirkit_unit03_navigation/pull/9
https://github.com/CIR-KIT-Unit03/cirkit_unit03_apps/pull/11
